### ISSUE TITLE
Use aide.wrapper in 24_aide.yml

### ISSUE THREAD

**Issue by tkreiner** [konstruktoid/ansible-role-hardening#12] opened 2018-10-30 12:44 UTC
I have been working with your Ansible project and it has been a great tool. I wanted to provide a suggestion for the tasks/24_aide.yml. (This is based on testing I am doing on a clean install of Ubuntu 16.04.5) You install the aidecheck.service that references the use of /usr/bin/aide.wrapper to run. Looking at that wrapper script, it points to a specific configuration at /var/lib/aide/aide.conf.default. In the "initialize aide" task in 24_aide.yml, you initialize the db using the regular aide command. In the instance I am testing with, aide by itself does not have a configuration associated with it. You may want to change the shell line of that task to instead be:

shell: aide.wrapper --init -B 'database_out=file:/var/lib/aide/aide.db.gz'

Output of aide -v showing no configuration (last line):

Aide 0.16a2-19-g16ed855

Compiled with the following options:

WITH_MMAP
WITH_POSIX_ACL
WITH_SELINUX
WITH_XATTR
WITH_E2FSATTRS
WITH_LSTAT64
WITH_READDIR64
WITH_ZLIB
WITH_MHASH
WITH_AUDIT
CONFIG_FILE = "/dev/null"

**Comment by konstruktoid** [comment] 2018-10-30 13:55
Hi and thanks @tkreiner, I'll look into it. 
The issue is that `aide.wrapper` doesn't exists on, for example, Fedora.

**Comment by konstruktoid** [comment] 2019-09-11 09:41
Believe this was fixed in
https://github.com/konstruktoid/ansible-role-hardening/commit/6148e9fe15dea3218beb7aba7017e953553cc03c#diff-4a66c43affc17e63c6f6e66a02620237

**Closed by konstruktoid** 2019-09-11 09:41 UTC
